# Generated by Django 5.2.5 on 2025-08-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career_advisor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="group",
            field=models.IntegerField(
                choices=[
                    (1, "Group 1"),
                    (2, "Group 2"),
                    (3, "Group 3"),
                    (4, "Group 4"),
                    (5, "Group 5"),
                    (6, "Group 6"),
                ],
                default=1,
                help_text="Question group (1-6)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("likert", "Likert Scale"),
                    ("single_choice", "Single Choice"),
                    ("multi_select", "Multi Select"),
                    ("text_input", "Text Input"),
                ],
                max_length=50,
            ),
        ),
    ]
